"""change_vector_dimension_to_1024

Revision ID: 66aaddcd5de0
Revises: 1e0f03676fa4
Create Date: 2025-03-17 00:53:44.319616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '66aaddcd5de0'
down_revision: Union[str, None] = '1e0f03676fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_information_chunks', 'embedding',
                    existing_type=Vector(1536),
                    type_=Vector(1024))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_information_chunks', 'embedding',
                    existing_type=Vector(1024),
                    type_=Vector(1536))
    # ### end Alembic commands ###
