name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t integration-app .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name integration-app-container integration-app

      - name: Run unit tests
        run: |
          docker exec integration-app-container bash -c "PYTHONPATH=/app poetry run pytest tests/test_views -v"
