name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 017820660583.dkr.ecr.us-east-1.amazonaws.com

    - name: Build, tag, and push the image to ECR
      run: |
        docker build -t integration-app .
        docker tag integration-repo:latest 017820660583.dkr.ecr.us-east-1.amazonaws.com/integration-repo:latest
        docker push 017820660583.dkr.ecr.us-east-1.amazonaws.com/integration-repo:latest

    - name: Update Lambda Function
      run: |
        aws lambda update-function-code --function-name integration-repo --image-uri 017820660583.dkr.ecr.us-east-1.amazonaws.com/integration-repo:latest
