name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Build, tag, and push the image to ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        IMAGE_NAME: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: latest
      run: |
        docker build -t $IMAGE_NAME .
        docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
        docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

    - name: Update Lambda Function
      env:
        FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        IMAGE_NAME: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: latest
      run: |
        aws lambda update-function-code --function-name $FUNCTION_NAME --image-uri $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
